### ISSUE TITLE
GettingStarted instructions does not work off-the-shelf (OSVR for Unity Developers)

### ISSUE THREAD

**Issue by peroht** [OSVR/OSVR-Unity#121]
The instructions (https://github.com/OSVR/OSVR-Unity/blob/master/GettingStarted.md) does not work "off-the-shelf" when a user tries to follow it lineary. 

The reason being that the default osvr_server_config.json uses direct mode but the unity package does not include the four files (glew32.dll, osvrRenderManager.dll, osvrUnityRenderingPlugin.dll, SDL2.dll). These have to be copied into the x86_64 plugin folder to make the instruction work.

I guess the simplest solution would be to change the osvr_server_config.json to not include rendermanager at first. Then further down in the documentation we should mention that the user has to copy the four dll's and to choose another osvr_server_config.json file. 

Another solution would be to include the four dll's in the unitypackage?

**Comment by DuFF14** [comment]
Recently changing the default osvr_server_config is what caused this issue. The rationale was that RenderManager and positional tracking should be supported by default, rather than neither of those. Ideally, all of those DLLs should be included in the unitypackage. I think the holdup now is adding OSVR-Unity-Rendering plugin to our CI. See https://github.com/OSVR/OSVR-Unity/issues/88

**Comment by DuFF14** [comment]
Fixed by CI changes following https://github.com/OSVR/OSVR-Unity/pull/130
