### ISSUE TITLE
Rendering: Do we leave the mono camera enabled?

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-Unity#47]
See this section of the latest Cardboard Unity support: https://github.com/googlesamples/cardboard-unity/blob/master/Cardboard/Scripts/StereoController.cs#L262

**Comment by DuFF14** [comment]
No, in stereo mode we disable the mono camera. Looks like they leave the mono camera enabled for part of the frame (but not rendering) so that it can be referenced easily by other game logic. Unity developers commonly use Camera.main to get the scene's main camera, but this usually assumes there is one camera in the scene. 

I really like the EndOfFrame coroutine as it provides a system for frame timing in Unity which will be crucial for rendering optimizations.

**Comment by russell-taylor** [comment]
One approach is to have a vector of cameras that has one in it for a mono viewpoint and two for stereo.  This could be generalized for a multi-zone stereo display.

**Comment by rpavlik** [comment]
I think there's probably value in adopting the approach used by the Cardboard plugin then, right?

**Comment by DuFF14** [comment]
Yes.

**Comment by DuFF14** [comment]
Working on this here: https://github.com/OSVR/OSVR-Unity/tree/enableCamera
Also added calls in the EndOfFrame coroutine to update the state of VRHead's tracker interface to see if it reduces perceived latency. To me, it feels the same or better in the demo scene. Will test in more complex scenes, and might make some more changes before opening a pull request. (I also am updating interfaces from LateUpdate in this branch exactly as in https://github.com/OSVR/OSVR-Unity/pull/64)
From the [docs](http://docs.unity3d.com/ScriptReference/WaitForEndOfFrame.html), WaitForEndOfFrame "Waits until the end of the frame after all cameras and GUI is rendered, just before displaying the frame on screen."
Also see [Execution Order of Event Functions](http://docs.unity3d.com/Manual/ExecutionOrder.html).

**Comment by DuFF14** [comment]
This was included with the DisplayConfig API update.
